In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("/StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
categorical_columns = [
    "gender",
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
]

In [6]:
for col in categorical_columns:
  df[col] = df[col].str.strip().str.title()

In [7]:
for col in categorical_columns:
  print(df[col].head())

0    Female
1    Female
2    Female
3      Male
4      Male
Name: gender, dtype: object
0    Group B
1    Group C
2    Group B
3    Group A
4    Group C
Name: race/ethnicity, dtype: object
0     Bachelor'S Degree
1          Some College
2       Master'S Degree
3    Associate'S Degree
4          Some College
Name: parental level of education, dtype: object
0        Standard
1        Standard
2        Standard
3    Free/Reduced
4        Standard
Name: lunch, dtype: object
0         None
1    Completed
2         None
3         None
4         None
Name: test preparation course, dtype: object

In [8]:
score_column = df[["math score","reading score","writing score"]]

In [9]:
score_column.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [10]:
df['total marks'] = df["math score"]+df["reading score"]+df["reading score"]

In [11]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total marks
0,Female,Group B,Bachelor'S Degree,Standard,None,72,72,74,216
1,Female,Group C,Some College,Standard,Completed,69,90,88,249
2,Female,Group B,Master'S Degree,Standard,None,90,95,93,280
3,Male,Group A,Associate'S Degree,Free/Reduced,None,47,57,44,161
4,Male,Group C,Some College,Standard,None,76,78,75,232

In [12]:
df['percentage'] = (df['total marks']/300)*100

In [13]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total marks,percentage
0,Female,Group B,Bachelor'S Degree,Standard,None,72,72,74,216,72.000000
1,Female,Group C,Some College,Standard,Completed,69,90,88,249,83.000000
2,Female,Group B,Master'S Degree,Standard,None,90,95,93,280,93.333333
3,Male,Group A,Associate'S Degree,Free/Reduced,None,47,57,44,161,53.666667
4,Male,Group C,Some College,Standard,None,76,78,75,232,77.333333

In [14]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total marks,percentage
995,Female,Group E,Master'S Degree,Standard,Completed,88,99,95,286,95.333333
996,Male,Group C,High School,Free/Reduced,None,62,55,55,172,57.333333
997,Female,Group C,High School,Free/Reduced,Completed,59,71,65,201,67.000000
998,Female,Group D,Some College,Standard,Completed,68,78,77,224,74.666667
999,Female,Group D,Some College,Free/Reduced,None,77,86,86,249,83.000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
 8   total marks                  1000 non-null   int64
 9   percentage                   1000 non-null   float64
dtypes: float64(1), int64(4), object(5)
memory usage: 78.3+ KB

In [16]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
total marks                    0
percentage                     0
dtype: int64

In [17]:

Q1 = df['math score'].quantile(0.25)
Q3 = df['math score'].quantile(0.75)
IQR = Q3 - Q1
outliers = df[(df['math score'] < (Q1 - 1.5 * IQR)) | (df['math score'] > (Q3 + 1.5 * IQR))]
print(f"Number of outliers in math score: {len(outliers)}")

Number of outliers in math score: 8